version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  api:
    restart: on-failure
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - ./backend/.env.docker
  frontend:
    restart: on-failure
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
