/**
 * TIRVerifier
 * Specifies the models and endpoints used in Trusted Issuer Registry resolution and issuer verification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A schema defining in more or less detail how a Verifiable Credential may look like.
 */
export interface CredentialSchema { 
    /**
     * A URI linking to an external resource containing the actual schema.
     */
    id: string;
    /**
     * A string defining the schema\'s type. As verifiable credentials are often presented in a JSON format, we expect \'JsonSchema\' to be a common value here, referring to the [JSON Schema specification](https://json-schema.org/).
     */
    type: string;
    /**
     * A SHA-256 hash of the external resource the \"id\" property refers to.
     */
    hash: string;
    /**
     * A boolean value that defines whether the trust defined in the schema can be delegated. This value is important in the event that the issuer operates its own TIR, a sub-registry, under its DID. If the schema is inheritable, the TIR also trusts the issuers in the issuer\'s sub-registry within the set schema restriction.
     */
    inheritable: boolean;
}

