/**
 * TIRVerifier
 * Specifies the models and endpoints used in Trusted Issuer Registry resolution and issuer verification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A small part of an issuer\'s path verification concerning one issuer of the path and one single verification, like whether a schema was found.
 */
export interface VerificationFraction { 
    /**
     * Describes in 1-2 words the type of verification.
     */
    title: string;
    /**
     * Whether the verification is valid, invalid, or in case of undefined, not performed
     */
    valid?: boolean;
    /**
     * A message giving details on the verification\'s result. For example: \"The verfication date is before the issuer\'s trustedSince timestamp.\"
     */
    message?: string;
}

