/**
 * TIRVerifier
 * Specifies the models and endpoints used in Trusted Issuer Registry resolution and issuer verification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Object containing the errors that lead to the verification being unsuccessful for this specific trust path issuer. For a successful trust path issuer verification, all properties must be true or undefined.
 */
export interface VerificationResultIssuerResultsInnerError { 
    /**
     * Whether the trust path issuer was not found in the resolved registry.
     */
    issuerNotFound: boolean;
    /**
     * Whether the trust path issuer\'s trust status is revoked.
     */
    issuerRevoked: boolean;
    /**
     * Whether the verification date is not between the trust path issuer\'s trustedSince and trustedUntil. Undefined if no verification date was given.
     */
    issuerNotTrustedAtThisDate?: boolean;
    /**
     * Whether no matching credential schema was found. Undefined if no VerifiableCredential was given for the verification.
     */
    noMatchingSchema?: boolean;
}

