/**
 * TIRVerifier
 * Specifies the models and endpoints used in Trusted Issuer Registry resolution and issuer verification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostVerifyRequest { 
    /**
     * The id of the issuer that should be verified.
     */
    id?: string;
    /**
     * An ISO 8601 timestamp for which the trustworthiness of the issuer is to be verified.
     */
    timestamp?: string;
    /**
     * A Verfiable Credential in JSON syntax, at least needed to check it against Credential Schemas. In case no id and/or timestamp is provided, \"issuer\" and \"issuanceDate\" properties from the VC will be used. JWT VCs must be decoded first (https://www.w3.org/TR/vc-data-model/#jwt-decoding).
     */
    vc?: object;
}

